-- Criando o banco do estoque
CREATE DATABASE ESTOQUE; 

-- Gerando a tabela 
CREATE TABLE ESTOQUE
(
	ID_PRODUTO INT PRIMARY KEY IDENTITY,
	NOME_PRODUTO VARCHAR(100) NOT NULL,
	QUANTIDADE_PRODUTO INT NOT NULL,
	UND_MEDIDA VARCHAR(10) NOT NULL,
	PRECO_CUSTO REAL NOT NULL,
	LUCRO_PRODUTO INT NOT NULL,
	PRECO_VENDA REAL NOT NULL,
	PRECO_TOTAL REAL NOT NULL
);

--Verifica se a tabela foi criada corretamente
SELECT * FROM dbo.ESTOQUE;